import axios from "axios";

//ACTION TYPE
const ADD_TO_ORDER = "ADD_TO_ORDER";
const CREATE_NEW_ORDER = "CREATE_NEW_ORDER";
const CHECKOUT = "CHECKOUT";
const GET_CUSTOMER = "GET_CUSTOMER";
const REMOVE_CUSTOMER = "REMOVE_CUSTOMER";
const REMOVE_PRODUCT = "REMOVE_PRODUCT";
const REMOVE_ONE = "REMOVE_ONE";
const DELETE_ALL = "DELETE_ALL";

//ACTION CREATORS

//MIDDLEWARE AND REDUX-THUNK

//REDUCER
